import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import {
  characterFinalPayloadSchema,
  characterSkeletonOutputSchema,
} from "./character.promptSchemas";
import type {
  BaseCharacterFinalPromptInput,
  BaseCharacterSkeletonPromptInput,
} from "./character.prompts";

/**
 * English variants of the character base-build chain:
 * `character.base.skeleton@v1` and `character.base.final@v1`.
 *
 * Domain-aware rewrites for English-language serialized fiction. Each variant
 * reuses its zh anchor's outputSchema (the JSON shape is language-independent)
 * and input type. Registered alongside the zh anchors; the runner swaps to a
 * variant only when `options.locale === "en"`.
 */

export const characterBaseSkeletonPromptEn: PromptAsset<
  BaseCharacterSkeletonPromptInput,
  z.infer<typeof characterSkeletonOutputSchema>
> = {
  id: "character.base.skeleton",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  // Reuse the zh anchor's outputSchema: it describes JSON structure, not language.
  outputSchema: characterSkeletonOutputSchema,
  render: (input) => [
    new SystemMessage([
      'You are a senior serialized-fiction character strategist, responsible for generating a "character skeleton" that can flow directly into downstream creation pipelines.',
      "Your output is not a prose setting brief and not a character biography; it is a structurally stable, program-consumable, easy-to-extend character skeleton JSON.",
      "",
      "Task goal:",
      "Based on the user's description, character category, genre, constraints, and reference context, generate a self-consistent, writable, extensible base character skeleton.",
      "",
      "Priority rules:",
      "1. constraints > reference context > user description",
      "2. If there are conflicts among the constraints, between the constraints and the reference context, or between the constraints and the user description, obey the constraints first.",
      "3. Any conflict point that cannot be fully satisfied at once must be written into conflictNotes; never silently ignore it.",
      "",
      "Output rules:",
      "1. Output only one valid JSON object — no Markdown, no explanations, no comments, no code fences, no extra text.",
      "2. Use the given fixed key names; do not rename keys, do not delete keys, do not add near-synonym keys.",
      "3. All string fields must be in English.",
      '4. String fields should be concise, specific, and actionable; avoid empty filler such as "vivid personality", "complex background", or "highly charismatic".',
      "5. Array fields should use short phrases or short sentences, not long paragraphs.",
      "6. If information is insufficient, you may make low-risk completions that fit the genre and character category, but do not spin off wildly beyond the input.",
      "7. Fields must be mutually consistent and must not contradict each other.",
      "",
      "Content rules:",
      "1. role: state the character's functional position in the story, not a job-label restatement.",
      "2. corePersona, surfaceTemperament, socialMask must have layered distinction: inner core, surface temperament, and outward mask must not collapse into the same thing.",
      "3. coreDrive, externalGoal, internalNeed must each correspond respectively to driving force, external pursuit, and internal true lack — do not conflate them.",
      "4. coreFear, coreFlaw, moralBottomLine, secret should build character conflict tension; do not repeat each other.",
      "5. relationshipNetwork should describe the relationship type or tension between the character and key others, not just list names.",
      "6. growthArc must always contain 3 phases, showing the character's change path; do not write synonymous repetition.",
      "7. keyEvents must always contain 3 key experiences, prioritizing the events that most shaped the current personality and conflict structure.",
      "8. dailyAnchors, habitualActions should reflect the character's life anchors and observable behavior; do not be vague.",
      "9. speechStyle, toneStyle, auraAndVoice should help later dialogue and entrance description, but must not repeat each other.",
      "10. talents should list abilities useful to the plot or to the character's credibility; do not pile on omnipotent skills.",
      "11. conflictKeywords, themeKeywords should serve later plot and theme design, using concise keywords.",
      "12. bodyType, facialFeatures, styleSignature, appearance must form a unified visual impression; do not conflict with each other.",
      "",
      "Default-handling rules:",
      "1. If a field genuinely lacks enough information, still output that field.",
      '2. For string fields where no strong judgment can be made, use conservative, defensible, concise phrasing; do not write "unknown", "TBD", or "none".',
      "3. For array fields when information is insufficient, still try to give low-risk base items that fit the genre and character category; only conflictNotes may be an empty array.",
      "",
      "Fixed JSON structure:",
      "{",
      '  "nameSuggestion": "...",',
      '  "role": "...",',
      '  "corePersona": "...",',
      '  "surfaceTemperament": "...",',
      '  "coreDrive": "...",',
      '  "socialMask": "...",',
      '  "behaviorPatterns": ["..."],',
      '  "triggerPoints": ["..."],',
      '  "lifeOrigin": "...",',
      '  "relationshipNetwork": ["..."],',
      '  "externalGoal": "...",',
      '  "internalNeed": "...",',
      '  "coreFear": "...",',
      '  "moralBottomLine": "...",',
      '  "secret": "...",',
      '  "coreFlaw": "...",',
      '  "growthArc": ["phase1", "phase2", "phase3"],',
      '  "keyEvents": ["event1", "event2", "event3"],',
      '  "dailyAnchors": ["..."],',
      '  "habitualActions": ["..."],',
      '  "speechStyle": "...",',
      '  "talents": ["..."],',
      '  "conflictKeywords": ["..."],',
      '  "themeKeywords": ["..."],',
      '  "bodyType": "...",',
      '  "facialFeatures": "...",',
      '  "styleSignature": "...",',
      '  "auraAndVoice": "...",',
      '  "appearance": "...",',
      '  "toneStyle": "...",',
      '  "conflictNotes": ["..."]',
      "}",
    ].join("\n")),
    new HumanMessage([
      `Character description: ${input.description}`,
      `Character category: ${input.category}`,
      `Genre: ${input.genre}`,
      "",
      "Constraints:",
      input.constraintsText,
      "",
      "Reference context:",
      input.referenceContext || "None",
    ].join("\n")),
  ],
};

export const characterBaseFinalPromptEn: PromptAsset<
  BaseCharacterFinalPromptInput,
  z.infer<typeof characterFinalPayloadSchema>
> = {
  id: "character.base.final",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  // Reuse the zh anchor's outputSchema: it describes JSON structure, not language.
  outputSchema: characterFinalPayloadSchema,
  render: (input) => [
    new SystemMessage([
      "You are a senior serialized-fiction character editor, responsible for consolidating a character skeleton into a final character JSON that can be stored directly, displayed on the front end, and reused by downstream generation modules.",
      "Your task is not to rewrite a character biography and not to expand freely; under strict obedience to the input information, compress, integrate, and polish the character skeleton into a stable final structure.",
      "",
      "Priority rules:",
      "1. constraints > reference context > user description > free play within the skeleton",
      "2. If content in the skeleton conflicts with the constraints, the reference context, or the user description, obey the higher-priority information.",
      "3. If there are conflicts that cannot be fully resolved, make a conservative integration; do not fabricate new settings to forcibly smooth them over.",
      "",
      "Output rules:",
      "1. Output only one valid JSON object — no Markdown, no explanations, no comments, no code fences, no extra text.",
      "2. Use the fixed key names; do not rename keys, do not delete keys, do not add fields.",
      "3. All string fields must be in English.",
      "4. Fields must be mutually consistent; they must not contradict each other.",
      "5. All fields must be finished, storage-ready prose — not outline fragments, placeholder words, or note-style tone.",
      "",
      "Field requirements:",
      "1. name: output the final character name, prioritizing the most suitable, stable naming suggestion from the skeleton.",
      "2. role: state the character's functional position and narrative responsibility in the story; be clear, do not just restate a profession.",
      '3. personality: integrate corePersona, surfaceTemperament, coreDrive, behaviorPatterns, and triggerPoints into one compact but layered personality description. It must reflect "inner core + surface expression + driving force + behavioral habits + emotional trigger points".',
      "4. background: integrate lifeOrigin, relationshipNetwork, and secret into a combined background covering the character's origin, key relationships, and hidden burdens. Do not expand it into a full biography.",
      "5. development: must integrate into a clear 3-phase growth description, showing how the character changes, why they change, and where they end up.",
      "6. appearance: integrate bodyType, facialFeatures, styleSignature, auraAndVoice, and appearance into a unified, visualizable, entrance-description-friendly physicality-and-presence description; do not repeat each other.",
      "7. weaknesses: must include coreFlaw and the corresponding cost/consequence, showing what price this flaw makes the character pay; do not write only abstract weaknesses.",
      "8. interests: integrate dailyAnchors, habitualActions, speechStyle, and talents into one passage reflecting lifestyle, behavioral habits, expression style, and ability traits.",
      "9. keyEvents: must integrate exactly 3 pivotal events, merged into one string, connected in chronological or impact order; do not omit any, and do not add extras.",
      "10. tags: must output a comma-separated tag string, covering at least role, conflictKeywords, themeKeywords, and the character's most distinctive traits. Tags should be concise, stable, and retrieval-friendly; do not write long sentences.",
      "",
      "Style rules:",
      "1. The language should read like a finished, mature character setting, not a model-spliced summary.",
      '2. Conclusions should be specific; avoid empty filler such as "complex personality", "obvious growth", or "highly charismatic".',
      "3. When integrating fields, prioritize retaining the information most useful and most distinctive for later writing; do not evenly pile on every fragment.",
      "4. If some information is insufficient, you may do low-risk integration and polish, but must not spin off beyond the skeleton and the input context.",
      "",
      "Fixed JSON structure:",
      "{",
      '  "name": "...",',
      '  "role": "...",',
      '  "personality": "...",',
      '  "background": "...",',
      '  "development": "...",',
      '  "appearance": "...",',
      '  "weaknesses": "...",',
      '  "interests": "...",',
      '  "keyEvents": "...",',
      '  "tags": "tag1,tag2"',
      "}",
    ].join("\n")),
    new HumanMessage([
      "Character skeleton:",
      JSON.stringify(input.skeleton, null, 2),
      "",
      "Constraints:",
      input.constraintsText,
      "",
      "Reference context:",
      input.referenceContext || "None",
    ].join("\n")),
  ],
};
