import type { WorldReferenceMode } from "@ai-novel/shared/types/worldWizard";
import type { WorldStructureSectionKey } from "@ai-novel/shared/types/world";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { PromptAsset } from "../../core/promptTypes";
import type {
  WorldAxiomSuggestionPromptInput,
  WorldConsistencyPromptInput,
  WorldDeepeningQuestionsPromptInput,
  WorldImportExtractionPromptInput,
  WorldInspirationConceptCardLocalizationPromptInput,
  WorldInspirationConceptCardPromptInput,
  WorldLayerGenerationPromptInput,
  WorldLayerLocalizationPromptInput,
  NovelThemeWorldGenerationPromptInput,
  WorldPropertyOptionsPromptInput,
  WorldReferenceInspirationPromptInput,
  WorldStructureBackfillPromptInput,
  WorldStructureSectionPromptInput,
  WorldVisualizationPromptInput,
} from "./world.promptTypes";
import {
  worldAxiomSuggestionSchema,
  worldConceptCardSchema,
  worldConsistencyIssuesSchema,
  worldDeepeningQuestionsSchema,
  worldImportExtractionSchema,
  worldLooseObjectSchema,
  novelThemeWorldGenerationSchema,
  worldPropertyOptionsPayloadSchema,
} from "./world.promptSchemas";
import { worldReferenceInspirationPayloadSchema } from "../../../services/world/worldReferenceSchema";
import { worldStructuredDataSchema, worldStructureSectionOutputSchema } from "../../../services/world/worldSchemas";
import { worldVisualizationDraftSchema } from "../../../services/world/worldVisualizationSchema";

/**
 * English variants of the `world.*` prompt family (world.prompts.ts anchors).
 *
 * Domain-aware rewrites for English-language fiction worldbuilding — NOT literal
 * string swaps of the zh anchors. Each variant reuses its zh anchor's
 * `outputSchema` (JSON shape is language-independent) and input type. Registered
 * alongside the zh anchors; the runner swaps to a variant only when
 * `options.locale === "en"`. postValidate stays on the anchor asset (the runner
 * invokes input.asset.postValidate), so language-independent validation still
 * runs on en output — en variants omit it, matching the F2 genre example.
 */

function buildReferenceModeLabelEn(mode: WorldReferenceMode | null | undefined): string {
  switch (mode) {
    case "extract_base":
      return "Extract the reference work's world base";
    case "tone_rebuild":
      return "Rebuild borrowing the reference work's tone & structure";
    case "adapt_world":
    default:
      return "Alternate-world adaptation from the reference work";
  }
}

/** English parallel of worldServiceShared.buildStructureSectionInstructions. */
function buildStructureSectionInstructionsEn(section: WorldStructureSectionKey): string {
  switch (section) {
    case "profile":
      return `Output only a JSON object shaped as:
{
  "summary": "...",
  "identity": "...",
  "tone": "...",
  "themes": ["..."],
  "coreConflict": "..."
}`;
    case "rules":
      return `Output only a JSON object shaped as:
{
  "summary": "...",
  "axioms": [{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],
  "taboo": ["..."],
  "sharedConsequences": ["..."]
}`;
    case "factions":
      return `Output only a JSON object shaped as:
{
  "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],
  "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}]
}
Extra constraints:
1. A faction is an abstract camp, stance, route, or world-side bloc — not an industry rule, social-pressure mechanism, or interpersonal norm.
2. A force is a concrete organization, circle, department, company, network, or agency — an action agent that can apply pressure, join conflicts, and relate to locations.
3. World-level mechanisms such as "social-pressure source", "industry operating rule", or "default interpersonal norm" belong in rules, not in factions / forces.`;
    case "locations":
      return `Output only a JSON array whose elements are shaped as:
[{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}]`;
    case "relations":
      return `Output only a JSON object shaped as:
{
  "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],
  "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]
}`;
    default:
      return "Output only valid JSON.";
  }
}

export const worldReferenceInspirationPromptEn: PromptAsset<
  WorldReferenceInspirationPromptInput,
  typeof worldReferenceInspirationPayloadSchema._output
> = {
  id: "world.reference.inspiration",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldReferenceInspirationPayloadSchema,
  render: (input) => [
    new SystemMessage([
      "You are a reference-work world analyst.",
      "Your task is NOT to rewrite an unrelated new story, but to distill from the reference material a \"preservable world base\" and \"decision boundaries usable for alternate-world adaptation\", providing a stable baseline for downstream worldbuilding.",
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "The output structure must be exactly:",
      "{",
      '  "conceptCard": {',
      '    "worldType": "...",',
      '    "templateKey": "custom",',
      '    "coreImagery": ["..."],',
      '    "tone": "...",',
      '    "keywords": ["..."],',
      '    "summary": "..."',
      "  },",
      '  "anchors": [',
      "    {",
      '      "id": "anchor-1",',
      '      "label": "...",',
      '      "content": "..."',
      "    }",
      "  ],",
      '  "seedPackage": {',
      '    "rules": [{"id":"reference-rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],',
      '    "factions": [{"id":"reference-faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["reference-force-1"]}],',
      '    "forces": [{"id":"reference-force-1","name":"...","type":"...","factionId":"reference-faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
      '    "locations": [{"id":"reference-location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["reference-force-1"]}]',
      "  }",
      "}",
      "",
      "Global hard rules:",
      "1. All text must be in English.",
      '2. conceptCard.templateKey is fixed to "custom"; do not change it.',
      "3. Distill only from the reference material; do not invent large world structures unsupported by the source.",
      "4. Low-risk generalization is allowed; never mistake specific plot beats, protagonist romance progression, or individual character motives for a world base.",
      '5. The output goal is a "world reference asset" — not a plot synopsis and not a genre-rewrite proposal.',
      "",
      "conceptCard requirements:",
      "1. worldType: summarize the reference world's basic type — stable, accurate, reusable.",
      "2. coreImagery: distill the most recognizable world imagery; prioritize scene-feel, order, oppression, industry texture, or social texture.",
      "3. tone: summarize the world's overall mood (e.g. hardboiled, oppressive, absurd, gritty, strictly ordered); no filler.",
      "4. keywords: distill world-layer keywords; prioritize institutions, environment, structure, ecology over plot words.",
      '5. summary: state "what should be preserved and what can be adapted"; name the world baseline worth borrowing and the mutable boundaries; do not generically rewrite the genre.',
      "",
      "anchors requirements:",
      "1. Provide 4-6 anchors — no fewer than 4, no more than 6.",
      "2. Prioritize covering core parts of: real-world base, city-location structure, social pressure, industry ecology, relationship structure, world boundaries.",
      '3. Every anchor must be a stable pin of the "world layer" or "world-story interface layer" that directly affects later adaptation decisions.',
      "4. Do not write specific plot beats, specific male/female-lead relationship progression, or a single character's private motive.",
      "5. label must be concise and clear; content must specifically state why this anchor is worth preserving or how it serves as an adaptation baseline.",
      "",
      "seedPackage general rules:",
      '1. seedPackage extracts "reference-world setting assets that can be directly reused or lightly adapted".',
      "2. rules, factions, forces, locations may all be empty arrays, but if the material has clearly extractable content, prefer preserving it; do not empty everything out of caution.",
      "3. Do not fabricate to fill structure; leave empty arrays when there is no basis.",
      "4. Prioritize extracting: world rules, faction stances, concrete organizations/forces, locations/scenes — these four reusable categories.",
      "",
      "rules requirements:",
      "1. Include only rules, orders, cost mechanisms, or run logic with real world-binding force.",
      "2. summary states the rule itself; cost states the cost of obeying/violating/using it; boundary states the applicable boundary; enforcement states how the rule is maintained.",
      "3. Do not mistake a protagonist's personal habit or a plot incident for a rule.",
      "",
      "factions requirements:",
      "1. Extract only camps with a stable stance, organization, or collective will in the world.",
      "2. position states its place in the world layout; doctrine states its core creed or value lean.",
      "3. goals and methods must show how this camp operates, competes, or applies pressure.",
      "",
      "forces requirements:",
      "1. forces are more concrete, story-landable organizations, departments, groups, power nodes, or action agents.",
      "2. Establish a clear affiliation with a faction where possible; otherwise handle conservatively.",
      "3. summary, baseOfPower, currentObjective, pressure, narrativeRole must be concrete and show the force's usable value in the world.",
      "",
      "locations requirements:",
      "1. Extract only locations with world recognizability and narrative function; do not grab random ordinary place names.",
      "2. summary states the location's traits; narrativeFunction states its story-layer use.",
      "3. risk, entryConstraint, exitCost must show how this location creates restriction, cost, or pressure.",
      "",
      "Quality requirements:",
      '1. The overall result must read like a "world reference breakdown card", not casually copied notes.',
      "2. conceptCard, anchors, seedPackage must be mutually consistent.",
      "3. Prioritize hard structures most useful for later world adaptation; do not get dragged off by trivial details.",
    ].join("\n")),
    new HumanMessage(input.userPrompt),
  ],
};

export const worldVisualizationPromptEn: PromptAsset<
  WorldVisualizationPromptInput,
  typeof worldVisualizationDraftSchema._output
> = {
  id: "world.visualization.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldVisualizationDraftSchema,
  render: (input) => [
    new SystemMessage([
      "You are a worldbuilding visualization extractor.",
      "Your task is to distill the world settings, faction relations, geographic structure, and temporal evolution in the input into structured JSON directly usable for visualization.",
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "The output structure must be exactly:",
      "{",
      '  "factionGraph": {',
      '    "nodes": [{"id":"faction-1","label":"...","type":"state|faction|race|organization|other"}],',
      '    "edges": [{"source":"faction-1","target":"faction-2","relation":"alliance|cooperation|support|opposition|hostility|subordination|suppression|trade|competition|neutral|affiliation"}]',
      "  },",
      '  "powerTree": [{"level":"L1","description":"..."}],',
      '  "geographyMap": {',
      '    "nodes": [{"id":"geo-1","label":"...","x":50,"y":50,"directionHint":"north|south|east|west|center|northeast|northwest|southeast|southwest","regionType":"continent|country|region|city|landmark|border|route|other","terrain":"...","summary":"...","parentId":null,"controllingForceIds":["faction-1"],"risk":"...","storyRelevance":"..."}],',
      '    "edges": [{"source":"geo-1","target":"geo-2","relation":"adjacent|passage|isolated|controlled","routeType":"road|river|sea|portal|trade|military|border|other","distanceHint":"...","direction":"north|south|east|west|center|northeast|northwest|southeast|southwest","risk":"..."}]',
      "  },",
      '  "timeline": [{"year":"...","event":"..."}]',
      "}",
      "",
      "Global hard rules:",
      "1. All label, relation, description, event, year values must be in English.",
      "2. Extract only information clearly present or low-risk inferable from the text; do not fabricate world structure.",
      '3. The output goal is "visualization-structure extraction" — not world appreciation and not plot summary.',
      "4. Parts must be mutually consistent; factionGraph, geographyMap, timeline must not contradict each other.",
      "",
      "factionGraph rules:",
      "1. Prioritize reflecting real force relations; do not replace explicit relations with vague general ones.",
      "2. Keep nodes between 4 and 12; prioritize core forces, key races, major organizations, or state actors.",
      "3. type may only be: state, faction, race, organization, other.",
      "4. edge.relation may only be: alliance, cooperation, support, opposition, hostility, subordination, suppression, trade, competition, neutral, affiliation.",
      "5. Do not pad node count with minor forces or one-off mentions of no narrative value.",
      "6. If the relation between two forces is unclear, do not force an edge.",
      "",
      "powerTree rules:",
      "1. powerTree extracts power hierarchy, strength ladder, governance structure, or resource-control structure.",
      "2. Each level should reflect its tier position, e.g. L1, L2, L3.",
      '3. description must state what power/strength tier this layer represents, not vague "upper"/"middle".',
      "4. If the text has no clear strength hierarchy, conservatively distill the most stable tier structure; do not force a complex grading system.",
      "",
      "geographyMap rules:",
      "1. geographyMap extracts spatial positions and connectivity between key locations, not a place-name list.",
      "2. nodes should prioritize core locations meaningful to world operation, force distribution, or story progression.",
      "3. x/y use 0-100 relative map coordinates: larger x = further east, larger y = further south; a central location is around 50/50.",
      "4. directionHint must roughly match x/y; when the text gives no clear direction, a conservative layout based on narrative tier is allowed, but do not pretend to have precise distances.",
      "5. regionType distinguishes continent, country, region, city, landmark, border, route, or other.",
      "6. edges.relation may only be: adjacent, passage, isolated, controlled.",
      "7. routeType marks road, river, sea route, portal, trade route, military route, border, or other; use other when there is no basis.",
      "8. Do not force pure plot scenes, one-off locations, or places with no spatial-structure value onto the map.",
      "9. If the relation between locations is unclear, do not force an edge.",
      "",
      "timeline rules:",
      "1. timeline extracts only important historical nodes, phase changes, or key events that affect the world layout.",
      '2. year may be a concrete year or a phase-style time expression, e.g. "late old era", "three years ago", "early new dynasty".',
      '3. event must concisely state "what changed"; do not write a long story.',
      "4. Do not mistake ordinary background exposition or local character experience for a world timeline node.",
      "",
      "Quality requirements:",
      '1. Prioritize "structure that lets the frontend draw a graph" over vague analysis.',
      "2. Be restrained with nodes and edges — fewer and clear beats a cluttered shelf.",
      "3. If a part genuinely lacks information, return an empty array; do not pad with fabricated content.",
      "4. ids must be stable, concise, and referenceable; the same node must line up correctly in edges.",
      "",
      "The output must strictly conform to worldVisualizationDraftSchema.",
    ].join("\n")),
    new HumanMessage(input.worldPromptSource),
  ],
};

export const worldInspirationConceptCardPromptEn: PromptAsset<
  WorldInspirationConceptCardPromptInput,
  typeof worldConceptCardSchema._output
> = {
  id: "world.inspiration.concept_card",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldConceptCardSchema,
  render: (input) => [
    new SystemMessage([
      "You are a worldbuilding inspiration concept-card distiller.",
      'Your task is to distill, from the input inspiration text, world-type hint, and available materials, a "world inspiration concept card" directly usable for later world design.',
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "All text fields must be in English.",
      "",
      "The output structure must be exactly:",
      "{",
      '  "worldType":"...",',
      `  "templateKey":"${input.templateKeysText}",`,
      '  "coreImagery":["..."],',
      '  "tone":"...",',
      '  "keywords":["..."],',
      '  "summary":"3-5 sentence summary"',
      "}",
      "",
      "Global hard rules:",
      "1. templateKey must be chosen from the given available values; do not invent, rewrite, or leave blank.",
      "2. Distill only from the input materials; do not invent a complete world setting from nothing.",
      "3. Low-risk generalization is allowed; never write vague impressions as overly strong conclusions.",
      '4. The output goal is a "world inspiration concept card" — not a plot synopsis, character setting, or world encyclopedia.',
      "",
      "Field requirements:",
      "1. worldType:",
      "   - Prefer combining worldTypeHint with the inspiration text.",
      "   - Summarize the world's basic type, e.g. urban-reality variant, post-apocalyptic wasteland, alternate dynasty, near-future high-pressure society.",
      "   - Keep it stable, accurate, usable for later routing; no vague big words.",
      "",
      "2. templateKey:",
      "   - Choose the best-fitting one among the given available templates.",
      "   - If the input mixes heavily, still pick the main template most able to carry later expansion.",
      "",
      "3. coreImagery:",
      "   - Extract 3-6 most recognizable world images.",
      '   - Prioritize spatial feel, order, industry texture, oppression, tech feel, religious feel, social texture — imagery "that lets you see this world at a glance".',
      "   - No plot beats; no single-character actions.",
      "",
      "4. tone:",
      "   - One short phrase capturing the world's overall mood, e.g. hardboiled-oppressive, ruined-chaotic, gorgeous-decayed, restrained-eerie.",
      '   - No filler like "very exciting" or "great atmosphere".',
      "",
      "5. keywords:",
      "   - Extract 4-8 keywords.",
      "   - Prioritize world structure, rule source, main oppression, run logic, social ecology, or core scent.",
      "   - Do not mechanically repeat coreImagery.",
      "",
      "6. summary:",
      "   - Must be a 3-5 sentence summary.",
      "   - State what core baseline is most worth preserving, what the first reading feel is, and which direction it suits for later expansion.",
      "   - Do not write a plot synopsis; do not generically restate the genre.",
      "",
      "Distillation principles:",
      '1. If the input is raw inspiration, prefer to "narrow the direction" for the user rather than keep diverging.',
      "2. If the input is already segmented extracts or carries retrieval materials, prefer preserving the most stable, most reusable world baseline.",
      "3. If information is insufficient, output a more stable concept card rather than force complex settings.",
      "4. Do not mistake character relations, specific event progression, or mainline conflict for a world concept.",
      "",
      "Quality requirements:",
      '1. The concept card should let the reader know "what kind of world this is, what scent it has, where it can go next".',
      "2. Fields must be internally consistent — worldType must not imply one world while tone and keywords feel like another.",
      "3. The result must fit the later world-design flow, not stay at the inspiration-jotting level.",
    ].join("\n")),
    new HumanMessage([
      `mode=${input.mode}`,
      `worldTypeHint=${input.worldTypeHint}`,
      `inspirationText=${input.promptText}`,
      `segmentedExtract=${input.extracted ? "yes" : "no"}`,
      `originalLength=${input.originalLength} chars`,
      `worldbuildingMaterialRetrieval=${input.ragContext || "none"}`,
    ].join("\n")),
  ],
};

export const worldInspirationConceptCardLocalizationPromptEn: PromptAsset<
  WorldInspirationConceptCardLocalizationPromptInput,
  typeof worldConceptCardSchema._output
> = {
  id: "world.inspiration.localize_concept_card",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldConceptCardSchema,
  render: (input) => [
    new SystemMessage([
      "You are a worldbuilding concept-card localization editor.",
      "Your task is to translate and polish the input concept-card content into natural, accurate English directly displayable and ready for continued use.",
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "",
      "You must strictly keep the original JSON structure; the output shape may only be:",
      "{",
      '  "worldType":"...",',
      '  "templateKey":"...",',
      '  "coreImagery":["..."],',
      '  "tone":"...",',
      '  "keywords":["..."],',
      '  "summary":"..."',
      "}",
      "",
      "Global hard rules:",
      "1. All display text must be rewritten into natural, fluent, accurate English.",
      "2. You must strictly preserve the original field names, field hierarchy, array lengths, and basic semantics; do not add, delete, or rename fields.",
      "3. templateKey is a structural field and must be kept as-is; do not translate, rewrite, or replace it.",
      "4. Do not change the concept card's original world-type judgment, imagery direction, mood positioning, or keyword meaning.",
      "5. Do not add new world settings, plot information, or explanatory content.",
      "",
      "Localization requirements:",
      "1. This is not a mechanical literal translation; rewrite it into natural expression fitting the English worldbuilding-planning context.",
      "2. If the original is obviously stiff, repetitive, translation-toned, or shows non-English thinking, polish it without changing the meaning.",
      "3. coreImagery and keywords should keep a short-word or short-phrase style — concise, recognizable; do not expand into long sentences.",
      "4. tone should read like a real mood description used in English planning, not a stiff translation.",
      "5. summary should keep the concept-card summary style — clear, condensed; do not write prose or a manual.",
      "",
      "Quality requirements:",
      "1. The output should read like a mature English world-inspiration concept card, not a translation draft.",
      "2. Fields must be internally consistent; never let worldType be one world while tone and keywords feel like another.",
      "3. If the input already contains natural English, prefer keeping it; do not force changes for the sake of translating.",
      "",
      "The output must strictly conform to worldConceptCardSchema.",
    ].join("\n")),
    new HumanMessage(input.conceptCardJson),
  ],
};

export const worldPropertyOptionsPromptEn: PromptAsset<
  WorldPropertyOptionsPromptInput,
  typeof worldPropertyOptionsPayloadSchema._output
> = {
  id: "world.property_options.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldPropertyOptionsPayloadSchema,
  render: (input) => {
    const isReferenceMode = Boolean(input.referenceMode);

    return [
      new SystemMessage(
        isReferenceMode
          ? [
              "You are a reference-work alternate-world adaptation planner.",
              'Your task is NOT to rewrite an unrelated new world, but to distill, from the reference work\'s world anchors, preservation requirements, and adaptation boundaries, the key world-decision items "that must be decided before formally generating the world".',
              "",
              "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
              "The output structure must be exactly:",
              "{",
              '  "options": [',
              "    {",
              '      "id": "optional",',
              '      "name": "Property name",',
              '      "description": "40-90 words on what this property decides and why it is worth choosing before generation",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "One line on why it deserves priority",',
              '      "choices": [{"id":"choice-a","label":"Direction A","summary":"How this direction adapts the reference world"}]',
              "    }",
              "  ]",
              "}",
              "",
              "Global hard rules:",
              "1. The number of options must exactly match the requested count.",
              "2. All text must be in English.",
              "3. targetLayer may only be: foundation, power, society, culture, history, conflict.",
              "4. Each option must carry 2-4 choices.",
              "5. choices must be mutually exclusive branches, not synonymous rewrites, strong/weak versions, or description-angle changes.",
              "6. Do not generate story-layer options like character motives, romance progression, specific beats, or single-chapter conflicts.",
              '7. Design decisions only around the "world layer" or "world-story interface layer".',
              "",
              "Decision-item requirements:",
              "1. Every option must be a real pre-decision that changes the later worldbuilding direction, not a fake option.",
              "2. name must be concise, clear, directly clickable; not a long phrase.",
              '3. description must state "what this property decides" and "why decide it now"; not vague.',
              "4. reason must one-line why it is a priority; do not repeat description.",
              "",
              "choices design rules:",
              "1. Every choice must represent a clear, forking adaptation route.",
              "2. choices must show genuinely different world paths, e.g. degree of reality retained, visibility of order, source of oppression structure, openness of rules, organization of the location system.",
              "3. Do not output near-synonym branches that differ only in wording.",
              '4. summary must state "how this branch will adapt the reference world" and point to boundaries and a sense of cost.',
              "",
              "Reference-adaptation principles:",
              "1. Decision items must revolve around the reference work's world base, not shell into an unrelated new world.",
              "2. Prioritize preserving the base structures that truly define the original's mood, then fork within the adaptable boundary.",
              "3. If a direction would distort the original's core mood, that boundary should appear in that choice.summary.",
              "4. Prioritize real world-affecting axes: reality base, city rules, social-oppression structure, location system, force network, public-vs-hidden boundaries.",
              "",
              "Quality requirements:",
              "1. options should spread across different targetLayers; do not cram all into one layer.",
              '2. Every option should let the user see at a glance "which world axis am I deciding".',
              "3. The output must directly serve the next world-generation step, not stay at concept-discussion level.",
              input.retryStrict
                ? "4. This round must strictly return JSON; if unsure, still give structured options — do not omit."
                : "",
            ].filter(Boolean).join("\n")
          : [
              "You are a pre-decision planner for a fiction world generator.",
              'Your task is to distill, before formally generating the world, a set of "key world-property options" genuinely worth deciding first.',
              "These options are not decorative questions but pre-decision axes that directly affect later worldbuilding direction.",
              "",
              "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
              "The output structure must be exactly:",
              "{",
              '  "options": [',
              "    {",
              '      "id": "optional",',
              '      "name": "Property name",',
              '      "description": "40-90 words on what this property decides and why it is worth choosing before generation",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "One line on why it deserves priority"',
              "    }",
              "  ]",
              "}",
              "",
              "Global hard rules:",
              "1. The number of options must exactly match the requested count.",
              "2. All text must be in English.",
              "3. targetLayer may only be: foundation, power, society, culture, history, conflict.",
              '4. Do not generate fake options too broad or with no real choice value, such as "world name", "world summary", "overall style".',
              "",
              "Property design requirements:",
              "1. Every option must be a concrete, choosable, direction-affecting key property.",
              "2. name must be concise and clear; the user must know at a glance what they are deciding.",
              "3. description must state which part of the world this property controls and why it deserves priority before generation.",
              "4. reason must one-line why it is a priority; do not synonym-repeat description.",
              "",
              "Generation principles:",
              '1. These options should continue the "pick properties first, fill details later" approach; prioritize real divergence points that shape the world.',
              "2. Properties should be as independent as possible, but together form a coherent world.",
              "3. Prioritize foundation, power, society, culture, history, conflict layers; do not pile all on one layer.",
              "4. Classic genre worldbuilding logic may be referenced, but avoid cliches and preserve recognizability.",
              "5. Decide by combining world type, template description, concept summary, core imagery, keywords, tone, and the user's raw inspiration.",
              "",
              "Quality requirements:",
              "1. Every property should let the user choose naturally after reading, without needing extra explanation.",
              '2. Do not output vague big words such as "world complexity", "setting depth", "story tension".',
              "3. The output must directly serve the next world-generation step, not stay at inspiration-discussion level.",
              input.retryStrict
                ? "4. This round must strictly return JSON; if unsure, still give structured options — do not omit."
                : "",
            ].filter(Boolean).join("\n")
      ),
      new HumanMessage(
        isReferenceMode
          ? [
              `Reference mode: ${buildReferenceModeLabelEn(input.referenceMode)}`,
              input.referenceAnchors && input.referenceAnchors.length > 0
                ? `Reference world anchors:\n${input.referenceAnchors.map((item) => `- ${item.label}: ${item.content}`).join("\n")}`
                : "",
              input.preserveElements && input.preserveElements.length > 0
                ? `Must preserve: ${input.preserveElements.join(", ")}`
                : "",
              input.allowedChanges && input.allowedChanges.length > 0
                ? `May adapt: ${input.allowedChanges.join(", ")}`
                : "",
              input.forbiddenElements && input.forbiddenElements.length > 0
                ? `Must not deviate from: ${input.forbiddenElements.join(", ")}`
                : "",
              `Generate ${input.optionsCount} key world-decision items "that must be decided before alternate-world adaptation".`,
              "Extra requirements:",
              "1. Every decision item must be a world-layer or world-story-interface adaptation axis.",
              "2. Each must give 2-4 mutually exclusive choices so the user can make a real route choice.",
              "3. choices must show different adaptation directions, not description-angle changes.",
              "4. Do not depart from the reference world base to reinvent an unrelated new world.",
            ].filter(Boolean).join("\n")
          : [
              `World type: ${input.worldType}`,
              `Template: ${input.templateName}`,
              `Template description: ${input.templateDescription}`,
              input.classicElements.length > 0 ? `Classic elements to reference: ${input.classicElements.join(", ")}` : "",
              input.pitfalls.length > 0 ? `Common pitfalls to avoid: ${input.pitfalls.join(", ")}` : "",
              `World concept summary: ${input.conceptSummary}`,
              input.coreImagery.length > 0 ? `Core imagery: ${input.coreImagery.join(", ")}` : "",
              input.keywords.length > 0 ? `Keywords: ${input.keywords.join(", ")}` : "",
              input.tone.trim() ? `Overall tone: ${input.tone.trim()}` : "",
              input.sourcePrompt.trim() ? `User's raw inspiration: ${input.sourcePrompt.trim()}` : "",
              input.ragContext?.trim() ? `Reference materials: ${input.ragContext.trim()}` : "",
              `Generate ${input.optionsCount} key world-property options "worth deciding before formally generating the world".`,
              "Extra requirements:",
              "1. Prioritize real world divergence points over broad items.",
              "2. Properties should spread across layers; together they form a complete world.",
              "3. Each property must let the user know at a glance what they are deciding.",
            ].filter(Boolean).join("\n")
      ),
    ];
  },
};

export const worldDeepeningQuestionsPromptEn: PromptAsset<
  WorldDeepeningQuestionsPromptInput,
  typeof worldDeepeningQuestionsSchema._output
> = {
  id: "world.deepening.questions",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldDeepeningQuestionsSchema,
  render: (input) => [
    new SystemMessage([
      "You are a worldbuilding follow-up question generator.",
      "Your task is to pick, from the current world setting, the 2-3 most worthwhile follow-up questions to help later world generation move forward.",
      "",
      "Output only one valid JSON array — no Markdown, explanations, comments, code blocks, or extra text.",
      "",
      "Each array item must strictly use this structure:",
      "{",
      '  "priority":"required|recommended|optional",',
      '  "question":"...",',
      '  "quickOptions":["...", "...", "..."],',
      '  "targetLayer":"foundation|power|society|culture|history|conflict",',
      '  "targetField":"..."',
      "}",
      "",
      "Global hard rules:",
      "1. Output only 2-3 questions — no fewer than 2, no more than 3.",
      "2. All text must be in English.",
      "3. Ask only based on the world name, description, existing data, and available reference materials in the input; do not diverge into unrelated directions.",
      '4. Questions must be "the gaps most worth asking before continuing world generation", not casual chat questions.',
      "",
      "Question design requirements:",
      "1. Every question must point to a real key gap that affects later worldbuilding direction.",
      "2. Prioritize questions that most determine world direction, rule form, social structure, conflict source, or historical baseline.",
      '3. Do not ask overly broad questions such as "what else do you want to add" or "what other traits does this world have".',
      "4. Do not ask character-motive, specific-plot-beat, or romance-progression story-layer questions unless they directly affect world-layer structure.",
      "",
      "priority rules:",
      "1. required: without this, later world generation is likely to drift or collapse.",
      "2. recommended: filling it clearly improves world completeness and writability, but short-term absence is survivable.",
      "3. optional: a nice-to-have supplement, not the current hardest gap.",
      "",
      "question rules:",
      "1. Must be a natural question the user can answer at a glance.",
      "2. Ask specifically and clearly; avoid abstract jargon.",
      "3. Each question should ask only one core point; do not cram multiple questions into one sentence.",
      "",
      "quickOptions rules:",
      "1. Must provide 2-4 concise candidate answers, all in English.",
      "2. quickOptions should help the user quickly pick a direction, not repeat the question.",
      "3. Different options must show a real fork, not synonymous rewrites.",
      "4. Keep options short, accurate, directly clickable; do not write long analyses.",
      "",
      "targetLayer rules:",
      "1. May only be chosen from foundation, power, society, culture, history, conflict.",
      "2. Must accurately match the world-structure layer this question mainly acts on.",
      "",
      "targetField rules:",
      "1. State clearly which concrete field or decision point this question fills.",
      '2. targetField should be concise and stable for later system consumption, e.g. "rule openness", "power source", "social control method", "historical rupture cause".',
      "",
      "Selection-priority principles:",
      '1. Prioritize "fewest questions, biggest gain".',
      "2. If dataJson is already fairly complete, do not re-ask already-clear information.",
      "3. If ragContext provides a strong reference direction, prioritize the key forks that decide how the reference material lands.",
      "4. The 2-3 questions should spread across different layers; do not cram all on one layer unless one layer is clearly the biggest gap.",
      "",
      "Quality requirements:",
      '1. The questions should make the user feel "these really hit the point".',
      "2. Do not pad the count with low-value questions.",
      "3. The overall result must be directly usable by the next world-completion flow.",
    ].join("\n")),
    new HumanMessage([
      `World name: ${input.worldName}`,
      `World description: ${input.description || "none"}`,
      `Current data: ${input.dataJson}`,
      `Available reference materials: ${input.ragContext || "none"}`,
    ].join("\n")),
  ],
};

export const worldConsistencyPromptEn: PromptAsset<
  WorldConsistencyPromptInput,
  typeof worldConsistencyIssuesSchema._output
> = {
  id: "world.consistency.check",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldConsistencyIssuesSchema,
  render: (input) => [
    new SystemMessage([
      "You are a worldbuilding consistency reviewer.",
      "Your task is to check whether the current world setting has clear conflicts, clashing rules, or high-risk inconsistencies, and output a structured issue list.",
      "",
      "Output only one valid JSON array — no Markdown, explanations, comments, code blocks, or extra text.",
      "If there are no issues, output only [].",
      "",
      "Each item structure must be exactly:",
      '{"severity":"warn|error","code":"...","message":"English issue summary","detail":"English detailed explanation","targetField":"description|background|geography|cultures|magicSystem|politics|races|religions|technology|conflicts|history|economy|factions"}',
      "",
      "Global hard rules:",
      "1. message and detail must be in English.",
      "2. Judge only from the given world axioms, core settings, and retrieval supplements; do not invent unprovided settings.",
      "3. Point out only real conflicts or clear risks; do not generalize and do not manufacture issues to pad the count.",
      "4. If evidence is insufficient, do not force a judgment.",
      "",
      "Review focus:",
      "1. Whether world axioms conflict with concrete settings.",
      "2. Whether different fields clash in rules, break causally, or are tier-incompatible.",
      "3. Whether settings create obviously unworkable, unsustainable, or mutually-canceling structural risks.",
      "4. Whether geography, politics, economy, religion, race, technology, magic, history, or conflict systems are notably inconsistent.",
      "",
      "severity rules:",
      "1. error: a clear conflict, things that cannot both hold, or that directly break the world's run logic.",
      "2. warn: not necessarily an absolute conflict now, but a clear high-risk point, an explanation gap, or a spot easy to break later.",
      "",
      "Field requirements:",
      "1. code: a concise, stable, reusable English/underscore-style issue code; not a long phrase.",
      "2. message: one line naming the core of the issue, readable at a glance.",
      "3. detail: specifically explain why this is an issue and between which two layers or fields the conflict occurs.",
      "4. targetField: must choose the main landing field from: description, background, geography, cultures, magicSystem, politics, races, religions, technology, conflicts, history, economy, factions.",
      "",
      "Quality requirements:",
      "1. Prioritize the most critical issues that would most affect later world generation and writing.",
      "2. If multiple issues are essentially the same, merge them; do not repeat the same class of risk.",
      "3. detail must be specific; do not just repeat message.",
      "4. The output must be directly usable by the later repair flow.",
    ].join("\n")),
    new HumanMessage([
      `World name: ${input.worldName}`,
      `World axioms: ${input.axioms || "none"}`,
      `Core settings: ${input.coreSettingsJson}`,
      `Retrieval supplements: ${input.ragContext || "none"}`,
    ].join("\n")),
  ],
};

export const worldLayerGenerationPromptEn: PromptAsset<
  WorldLayerGenerationPromptInput,
  typeof worldLooseObjectSchema._output
> = {
  id: "world.layer.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldLooseObjectSchema,
  render: (input) => [
    new SystemMessage(
      [
        `You are a worldbuilding layered constructor; you are currently only responsible for generating the fields for layer=${input.layerKey}.`,
        "Your task is NOT to rewrite the whole world, but to fill, on top of the existing world, a structured setting for the current layer that is directly usable for novel writing.",
        "",
        "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
        `Output fields may only come from: ${input.targetFields.join(", ")}.`,
        "Do not add fields or output any keys outside the target fields.",
        "Each field's value must be an English text string directly displayable to the author.",
        "Do not write field values as JSON objects, arrays, nested structures, key-value tables, or code-style structures.",
        "If a layer naturally contains multiple entries, express them in the same string with natural-language paragraphing or line breaks; do not output nested objects.",
        "",
        "Global hard rules:",
        "1. Strictly obey: world axioms, template constraints, the user's prior blueprint choices, and existing generated content.",
        "2. Only complete and refine on the existing base; do not overturn settings already established by earlier layers.",
        "3. If input information is insufficient, complete conservatively; prioritize low-risk, viable settings; do not diverge wildly.",
        "4. All field values must be in English.",
        "5. The output must be a result that drops directly into the world-setting store, not analysis notes or a summary.",
        "",
        "Generation principles:",
        "1. The current layer must form a causal, structural, or operational link with earlier layers; do not write it as isolated description.",
        '2. Each field should answer "how does this world concretely run", not just label concepts.',
        "3. Prioritize settings that genuinely affect later plot, characters, conflict, resource flow, or order.",
        '4. Do not write vague expressions such as "complex society", "diverse culture", "faction strife". State specifically what is complex, what is diverse, how they clash.',
        "",
        "Consistency requirements:",
        "1. Do not conflict with content already in existing.",
        "2. If a setting must carry forward a direction in blueprint or summary, explicitly show that carry-forward.",
        "3. If classicElements are referenceable, absorb their effective structure, but do not mechanically read back the template description.",
        "4. If pitfalls flag common traps, actively avoid them; do not write the risk straight into the setting.",
        "",
        "Quality requirements:",
        "1. Every field must be concrete, clear, usable for writing; do not stop at encyclopedic empty description.",
        "2. Settings should show the world's run logic, constraint boundaries, and narrative value.",
        "3. If the current layer naturally depends on upper-layer settings, explicitly show that dependence rather than starting fresh.",
        "",
        "Boundary rules:",
        "1. Do not output summary paragraphs, prefaces, afterwords, or explanations.",
        "2. Do not fill settings outside targetFields.",
        "3. Do not leave fields empty due to insufficient information; try to give stable usable content.",
      ].join("\n")
    ),
    new HumanMessage(
      [
        `name=${input.worldName}`,
        `worldType=${input.worldType}`,
        `template=${input.templateName}`,
        `templateDescription=${input.templateDescription}`,
        `classicElements=${input.classicElements.join(" | ") || "none"}`,
        `pitfalls=${input.pitfalls.join(" | ") || "none"}`,
        `axioms=${input.axioms || "none"}`,
        `summary=${input.summary || "none"}`,
        "blueprint=",
        input.blueprintPromptBlock,
        `existing=${input.existingJson}`,
        `ragContext=${input.ragContext || "none"}`,
        "",
        `Generate only the fields needed for the current layer=${input.layerKey}, and ensure fields come only from: ${input.targetFields.join(", ")}.`,
      ].join("\n")
    ),
  ],
};

export const worldLayerLocalizationPromptEn: PromptAsset<
  WorldLayerLocalizationPromptInput,
  typeof worldLooseObjectSchema._output
> = {
  id: "world.layer.localize",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldLooseObjectSchema,
  render: (input) => [
    new SystemMessage(
      [
        "You are a worldbuilding setting-text localization assistant.",
        'Your task is to rewrite all "fields shown to the user" in the input JSON object into natural, accurate English directly usable for display and continued use.',
        "",
        "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
        "",
        "Structure hard rules:",
        "1. Keep field names exactly unchanged.",
        "2. Do not add, delete, or reorder fields, or change the hierarchy.",
        `3. Output fields may only come from the current layer's allowed fields: ${input.layerFields.join(", ")}.`,
        "",
        "Content rules:",
        "1. Preserve the original setting semantics; do not change world rules, structural relations, causal logic, or setting boundaries.",
        "2. Preserve the meaning of proper nouns; if a proper noun already has a reasonable English form, prefer natural English expression.",
        "3. Do not add new settings or cut existing valid information.",
        "4. Do not arbitrarily specify vague wording into a new world fact.",
        "",
        "Localization requirements:",
        "1. All field values must be rewritten into English.",
        "2. This is not a mechanical translation; rewrite it into natural expression fitting the English fiction-worldbuilding context.",
        "3. If the original has non-English thinking, stiff literal translation, repetition, or awkward expression, optimize it without changing the meaning.",
        "4. Each item in an array must also be localized, but keep the original count and correspondence unchanged.",
        "",
        "Quality requirements:",
        "1. The output must read like an English finished draft ready for the world-setting store, not a translation draft.",
        "2. Field values must be mutually consistent; never let terminology drift.",
        "3. Do not output vague polish; prioritize accuracy, stability, reusability.",
        "",
        "Boundary rules:",
        "1. If some values are already natural English, keep them or only lightly polish; do not change for the sake of changing.",
        "2. If some ID/code-style field values are structural identifiers rather than display text, do not mistranslate them.",
      ].join("\n")
    ),
    new HumanMessage(
      [
        `layer=${input.layerKey}`,
        `fields=${input.layerFields.join(",")}`,
        `input=${input.sourcePayloadJson}`,
      ].join("\n")
    ),
  ],
};

export const worldImportExtractionPromptEn: PromptAsset<
  WorldImportExtractionPromptInput,
  typeof worldImportExtractionSchema._output
> = {
  id: "world.import.extract",
  version: "v1",
  taskType: "fact_extraction",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldImportExtractionSchema,
  render: (input) => [
    new SystemMessage([
      "You are a worldbuilding import extractor.",
      "Your task is to extract a world-setting JSON directly importable into the system from the input text.",
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "",
      "The output fields must be exactly:",
      "name, description, worldType, background, geography, magicSystem, politics, cultures, races, religions, technology, history, economy, conflicts, factions, templateKey, axioms.",
      "",
      "Global hard rules:",
      "1. All display text must be in English.",
      "2. Extract only information clearly present or low-risk generalizable from the input text; do not fabricate a complete setting from nothing.",
      "3. If a field lacks sufficient basis in the source, handle it conservatively — prefer an empty string, empty array, or minimal viable content; do not force-fabricate.",
      '4. The output goal is "world-setting import" — not an article summary and not an appreciation report.',
      "5. Fields must be mutually consistent; do not conflict.",
      "",
      "Field extraction principles:",
      "1. name: extract the world name; if not explicit, use the safest, most text-fitting summary name; do not invent flashy names.",
      "2. description: summarize the world's overall face and core traits — concise but specific; no filler.",
      "3. worldType: extract the world's basic type, e.g. urban variant, alternate dynasty, post-apocalyptic wasteland, near-future high-pressure society; stable, accurate, usable for later classification.",
      "4. background: extract the world's formation background, era situation, fundamental situation, or major-environment premise.",
      "5. geography: extract key geographic layout, spatial structure, regional distribution, or location systems.",
      "6. magicSystem: extract extraordinary systems, power rules, ability sources, costs, and boundaries; if none, leave empty conservatively.",
      "7. politics: extract polity, power structure, governance, ruling relations, or political opposition.",
      "8. cultures: extract customs, values, social habits, etiquette, taboos, or cultural stratification.",
      "9. races: extract races, ethnic groups, class-type biological groups, or special-population divisions; if none, leave empty.",
      "10. religions: extract religions, belief systems, mythic worship, sacrificial order, or sources of spiritual authority; if none, leave empty.",
      "11. technology: extract tech level, productivity form, tool systems, industrial/information/mechanical traits.",
      "12. history: extract key historical phases, ruptures, major events, legacy of old orders, or historical trauma.",
      "13. economy: extract resource flow, wealth sources, industry structure, exchange mechanisms, survival cost, or economic-oppression structure.",
      "14. conflicts: extract world-layer core contradictions, long-term conflict sources, structural opposition — not single plot events.",
      "15. factions: extract stably existing forces, organizations, states, camps, blocs, or power actors.",
      "16. templateKey: conservatively classify into the closest template key by content; if the text lacks basis, use the safest default classification; do not invent template names.",
      "17. axioms: extract world axioms, hard rules, inviolable base constraints, or default run logic.",
      "",
      "Extraction quality requirements:",
      "1. Prioritize hard-structure information most useful for later novel writing, over trivial details.",
      "2. Do not mistake a character's personal experience, specific plot beat, or single event for a world-layer field.",
      "3. Do not make adjacent fields synonym-repeat (e.g. background, history, description should not just rephrase the same paragraph).",
      "4. If the input text is clearly plot-synopsis-leaning, still try to extract only world-layer information, filtering character-line and plot-line noise.",
      "",
      "Missing-handling rules:",
      "1. When unsure, prefer conservative; do not fabricate.",
      "2. When there is no clear religion/race/magic/tech content, do not force-generate for structural completeness.",
      "3. If factions can be extracted as an array or list, preserve them as usable structural descriptions rather than vague summaries.",
      "",
      "The output must strictly conform to worldImportExtractionSchema.",
    ].join("\n")),
    new HumanMessage(input.content),
  ],
};

export const worldStructureBackfillPromptEn: PromptAsset<
  WorldStructureBackfillPromptInput,
  typeof worldStructuredDataSchema._output
> = {
  id: "world.structure.backfill",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldStructuredDataSchema,
  render: (input) => [
    new SystemMessage([
      "You are a world structure extractor.",
      "Your task is to extract, from the input text, world-structure data directly usable in the system.",
      "This is not appreciation, summary, or free-form completion — it organizes the world-layer information in the text into a stable JSON structure.",
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "The JSON structure must be exactly:",
      "{",
      '  "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '  "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '  "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],',
      '  "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
      '  "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}],',
      '  "relations": {',
      '    "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],',
      '    "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]',
      "  }",
      "}",
      "",
      "Global hard rules:",
      "1. Extract only information clearly present or low-risk inferable in the text; do not fabricate a complete world structure.",
      "2. All values must be in English.",
      "3. Do not add fields, rename fields, or delete field hierarchy.",
      "4. If a category is genuinely missing, return an empty array or minimal viable content conservatively; do not force-fabricate.",
      "5. Parts must be mutually consistent; do not conflict.",
      "",
      "Field-judgment rules:",
      '1. profile: summarizes this world\'s overall identity, mood, themes, and core conflict — from the "world layer", not the "character layer".',
      "2. rules: extracts the rules, costs, boundaries, taboos, and shared consequences that hold by default in this world.",
      "3. factions: abstract camps, stances, routes, class blocs, or ideological camps.",
      "4. forces: concrete organizations, circles, companies, departments, gangs, agencies, networks, or landable action agents.",
      "5. locations: places with world recognizability and narrative function, not casually-mentioned ordinary scenes.",
      "6. relations: extracts relations between forces, and the control relations of a force over a location.",
      "",
      "Key distinction requirements:",
      '1. World-default mechanisms like "social-pressure mechanism", "industry operating rule", "default interpersonal norm", "survival cost", "resource constraint" must go into rules, not factions or forces.',
      "2. A faction states 'which kind of people / stance / route'; a force states 'who specifically executes, controls, applies pressure'.",
      "3. If an object has only an abstract stance with no clear organizational entity, prefer factions; if it can appear as a concrete action unit, prefer forces.",
      "",
      "profile requirements:",
      "1. summary: summarize the world's most core face and running reality; do not write a plot synopsis.",
      "2. identity: state this world's basic identity, e.g. industrial-wasteland city, power-high-pressure dynasty, industry-jungle society.",
      "3. tone: write the world's overall mood, e.g. hardboiled, oppressive, gritty, decayed, eerie; no filler.",
      "4. themes: extract world-layer themes; do not write single-character propositions.",
      "5. coreConflict: the world's most core, longest-standing structural contradiction.",
      "",
      "rules requirements:",
      "1. axioms includes only rules with real world-binding force.",
      "2. Each axiom must state: what the rule is, what the cost is, where the boundary is, and how it is maintained.",
      "3. taboo is the explicit no-touch taboos, red lines, or high-pressure triggers in the world.",
      "4. sharedConsequences are the default consequences or systemic costs most people share in this world.",
      "",
      "factions / forces requirements:",
      "1. factions must show stance, creed, goal, and method differences; do not make vague labels.",
      "2. representativeForceIds should correspond to the concrete force truly representing that faction.",
      "3. forces must state power source, current objective, pressure method, and narrative role.",
      "4. With no clear leader, handle conservatively; do not invent names.",
      "",
      "locations requirements:",
      "1. Keep only genuinely important locations.",
      "2. summary states the location's traits; narrativeFunction states its story-layer use.",
      "3. risk, entryConstraint, exitCost must show why this location has a threshold, pressure, or cost.",
      "",
      "relations requirements:",
      "1. forceRelations records only genuinely meaningful relations; do not mechanically connect all objects.",
      "2. relation states the relation type; tension states the current tension point; detail states why the relation holds.",
      "3. locationControls only when the text supports a control / occupation / management / blockade / infiltration relation between a force and a location.",
      "",
      "Quality requirements:",
      "1. Prioritize hard-structure information most useful for later creation, over trivial details.",
      "2. Do not write character personal motives, specific plot beats, or romance progression into the world structure.",
      "3. Do not let profile, rules, factions, forces rephrase-repeat each other.",
      "4. The output must read like a world-structure draft directly storable, not reading notes.",
    ].join("\n")),
    new HumanMessage(input.promptSource),
  ],
};

export const novelThemeWorldGenerationPromptEn: PromptAsset<
  NovelThemeWorldGenerationPromptInput,
  typeof novelThemeWorldGenerationSchema._output
> = {
  id: "novel.world.generate_from_theme",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: novelThemeWorldGenerationSchema,
  render: (input) => [
    new SystemMessage([
      "You are a this-book world designer for fiction.",
      'Your task is to generate, from a novel\'s theme, selling points, reader promises, and genre information, world-structure data "for this book\'s exclusive use".',
      "This is not an external world-library encyclopedia and not a plot outline; the output must serve later character, outline, chapter, and consistency generation.",
      "",
      "Output only one valid JSON object — no Markdown, explanations, comments, code blocks, or extra text.",
      "The output structure must be exactly:",
      "{",
      '  "title": "...",',
      '  "coverSummary": "...",',
      '  "worldType": "...",',
      '  "structuredData": {',
      '    "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '    "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '    "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],',
      '    "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
      '    "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}],',
      '    "relations": {',
      '      "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],',
      '      "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]',
      "    }",
      "  }",
      "}",
      "",
      "Global hard rules:",
      "1. All text must be in English.",
      "2. The world must tightly fit this book's theme; do not generate a generic encyclopedia unrelated to the novel's selling points.",
      "3. The world setting must constrain later generation: power has cost, order has enforcers, conflict has a source, locations have narrative function.",
      "4. Do not write the protagonist's personal plot; do not generate a complete outline for the novel; do not treat a single event as a world rule.",
      "5. Reasonable completion based on novel info is allowed; if information is insufficient, generate a stable, low-risk, extensible stage for this book.",
      "",
      "Content-count requirements:",
      "1. rules.axioms: generate 3-5.",
      "2. factions: generate 2-4 abstract camps or stance blocs.",
      "3. forces: generate 3-6 concrete forces, organizations, agencies, or action agents.",
      "4. locations: generate 3-6 stage locations that recur in this book.",
      "5. relations: connect only genuinely meaningful force relations and location controls; do not mechanically fully-connect.",
      "",
      "Field quality requirements:",
      "1. title should read like a displayable world name, not just the novel's name.",
      "2. coverSummary: 1-2 sentences on the world face the reader sees at a glance.",
      '3. profile.summary: state "what this world looks like, how it runs, why it fits this book".',
      "4. Each rules axiom must state rule, cost, boundary, and enforcement.",
      "5. A faction is a stance or class bloc; a force is a concrete executor; do not conflate.",
      "6. A location must have risk, entry threshold, exit cost, or narrative function.",
      "7. forbidden/taboo/sharedConsequences should help later generation avoid breaking world rules.",
      "",
      "Generation-chain-facing requirements:",
      "1. Character generation should be able to find identity, affiliation, and conflict source from forces/factions.",
      "2. Outline generation should be able to find stage and long-term contradiction from locations/coreConflict.",
      "3. Chapter generation should be able to get inviolable constraints from rules/taboo/sharedConsequences.",
      "4. This world is a this-book copy that can later be saved to the world library; do not assume it is already a generic template.",
    ].join("\n")),
    new HumanMessage([
      `Novel title: ${input.novelTitle}`,
      `Novel description: ${input.description || "not filled"}`,
      `Target readers: ${input.targetAudience || "not filled"}`,
      `Core selling point: ${input.bookSellingPoint || "not filled"}`,
      `First-30-chapter promise: ${input.first30ChapterPromise || "not filled"}`,
      `Commercial tags: ${input.commercialTags.length > 0 ? input.commercialTags.join(", ") : "not filled"}`,
      `Main genre: ${input.genreName || "not selected"}`,
      `Primary story mode: ${input.primaryStoryModeName || "not selected"}`,
      `Secondary story mode: ${input.secondaryStoryModeName || "not selected"}`,
      input.storyMacroContext?.trim() ? `Story macro plan:\n${input.storyMacroContext.trim()}` : "",
      input.bookContractContext?.trim() ? `Book creation contract:\n${input.bookContractContext.trim()}` : "",
    ].join("\n")),
  ],
};

export const worldStructureSectionPromptEn: PromptAsset<
  WorldStructureSectionPromptInput,
  typeof worldStructureSectionOutputSchema._output
> = {
  id: "world.structure.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldStructureSectionOutputSchema,
  render: (input) => [
    new SystemMessage(
      [
        `You are a world-structure completion agent; you are currently only responsible for completing the JSON for section=${input.section}.`,
        "Your task is NOT to rewrite the whole world structure, but to fill, on top of the existing structure, structured content directly storable for the specified section.",
        "",
        "Output only one valid JSON — no Markdown, explanations, comments, code blocks, or extra text.",
        "",
        buildStructureSectionInstructionsEn(input.section),
        "",
        "Global hard rules:",
        "1. Complete only the data for the current section; do not output other sections' content.",
        "2. Do not break existing IDs; if reusing existing entities, you must reuse the ids in the current structure.",
        "3. Do not fabricate information that clearly conflicts with the input text, current structure, or binding advice.",
        "4. If information is insufficient, complete conservatively; prioritize 'low-risk, viable, landable' structure; do not force complex settings.",
        "5. All text values must be in English.",
        "",
        "Consistency requirements:",
        "1. The output must be continuous with the current structure; do not overturn established world rules, faction relations, location functions, or existing bindings.",
        "2. If the current section involves entity reuse, prefer continuing existing naming, affiliation, and relation networks.",
        "3. If the current binding advice gives a priority connection direction, follow it unless it clearly conflicts with the input text.",
        "",
        "Section completion rules:",
        "1. If section=factions, consider the distinction and linkage between factions and forces together.",
        "2. World-default mechanisms such as social-pressure mechanisms, industry rules, interpersonal norms, default order, or universal cost belong in rules; do not write them into factions / forces.",
        "3. A faction is an abstract camp, stance, or route; a force is a concrete action agent such as an organization, department, circle, company, gang, agency, or network.",
        "4. If section=locations, you must fill narrativeFunction, risk, entryConstraint, exitCost, and they must be concrete and usable, not vague.",
        "5. If section=relations, only forceRelations and locationControls may be output; do not add other relation blocks.",
        "6. relations must connect only entities with real basis; do not mechanically connect.",
        "",
        "Quality requirements:",
        "1. The output must read like a finished draft directly entering the world-structure store, not analysis notes.",
        '2. Every field must be concrete, stable, usable for later creation; avoid hollow phrases like "complex forces", "dangerous locations", "tense relations".',
        "3. Prioritize hard structure that truly affects world operation and narrative progression; do not get led off by trivial details.",
        "4. If the current section naturally depends on other sections, show that structural link rather than writing in isolation.",
      ].join("\n")
    ),
    new HumanMessage(
      [
        input.promptSource,
        "",
        "Current structure:",
        JSON.stringify(input.currentStructure, null, 2),
        "",
        "Current binding advice:",
        JSON.stringify(input.currentBindingSupport, null, 2),
      ].join("\n"),
    ),
  ],
};

export const worldAxiomSuggestionPromptEn: PromptAsset<
  WorldAxiomSuggestionPromptInput,
  typeof worldAxiomSuggestionSchema._output
> = {
  id: "world.axioms.suggest",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "en",
  contextPolicy: { maxTokensBudget: 0 },
  outputSchema: worldAxiomSuggestionSchema,
  render: (input) => [
    new SystemMessage([
      "You are a world-axiom designer.",
      'Your task is to generate 5 "core axioms" for the current world, as the highest constraint layer for later worldbuilding, setting completion, and plot expansion.',
      "",
      "Output only one valid JSON array — no Markdown, explanations, comments, code blocks, or extra text.",
      "Array elements must all be strings and all in English.",
      "Output exactly 5 — no more, no less.",
      "",
      "Global hard rules:",
      '1. Every axiom must be a hard rule "that can constrain later generation", not a slogan, theme sentence, or world intro.',
      "2. Axioms must directly affect later worldbuilding — e.g. limit cost, prescribe order, define conflict source, draw boundary conditions, or clarify default consequences.",
      "3. Generate only from the world type, template description, world summary, and blueprint constraints in the input; do not spin off a different world.",
      "4. If information is insufficient, prioritize low-risk, general but binding axioms; do not diverge vaguely.",
      "",
      "Axiom design requirements:",
      "1. Cover most of these key constraints: cost, order, conflict source, boundary conditions, default consequences, resource constraints, power limits, public vs hidden rules.",
      '2. Each axiom should answer "how does this world run by default, what happens when violated, what cannot happen without cost".',
      "3. Axioms must be concrete — they may constrain power use, identity mobility, resource acquisition, organizational order, information spread, social oppression, or boundary-crossing cost.",
      '4. Do not write vague judgments like "the world is cruel", "human hearts are complex", "the strong rule" unless concretized into an executable constraint.',
      "5. The 5 axioms should divide labor clearly; do not rephrase-repeat the same meaning.",
      "",
      "Expression requirements:",
      "1. Write each axiom as one complete, clear, directly quotable constraint sentence.",
      "2. Do not write too long, but be specific enough to constrain later world generation.",
      "3. The language should read like base rules in a world setting, not promo copy or literary lyricism.",
      "",
      "Quality requirements:",
      "1. After reading these 5, one should roughly understand this world's operational baseline.",
      "2. These axioms should help later auto-generation avoid drifting, avoid setting distortion, and avoid costless freebies.",
      "3. Do not generate mutually conflicting axioms.",
    ].join("\n")),
    new HumanMessage([
      `worldName=${input.worldName}`,
      `worldType=${input.worldType}`,
      `template=${input.templateName}`,
      `templateDescription=${input.templateDescription}`,
      `worldSummary=${input.description}`,
      "Blueprint constraints:",
      input.blueprintPromptBlock,
    ].join("\n")),
  ],
};
